<?php

namespace hotsweek\builder;

use hotsweek\builder\BuilderCommon;

class BaseDataBuilder extends BuilderCommon
{
    protected $presets = [
        SET => [
            ['last_game_time', TIMESTAMP, true],
        ],
        COUNTER => [
            ['game_length', GAME_LENGTH],
            ['game_total', INC],
            ['game_win', INC, WIN],
            ['team1_count', INC, 'Team'],
            ['party_total', INC, PARTY],
            ['party_win', INC, PARTY_WIN],
        ],
        COUNTER_SR => [
            ['Level'],
            ['Takedowns'],
            ['SoloKills'],
            ['Assists'],
            ['Deaths'],
            ['HighestKillStreak'],
            ['HeroDamage'],
            ['SiegeDamage'],
            ['StructureDamage'],
            ['MinionDamage'],
            ['CreepDamage'],
            ['SummonDamage'],
            ['TimeCCdEnemyHeroes'],
            ['Healing'],
            ['SelfHealing'],
            ['DamageTaken'],
            ['DamageSoaked'],
            ['ExperienceContribution'],
            ['TownKills'],
            ['TimeSpentDead'],
            ['MercCampCaptures'],
            ['WatchTowerCaptures'],
            ['MetaExperience'],
        ],
        COUNTER_MSRED => [
            ['ProtectionGivenToAllies'],
            ['TimeSilencingEnemyHeroes'],
            ['TimeRootingEnemyHeroes'],
            ['TimeStunningEnemyHeroes'],
            ['ClutchHealsPerformed'],
            ['EscapesPerformed'],
            ['VengeancesPerformed'],
            ['TeamfightEscapesPerformed'],
            ['OutnumberedDeaths'],
            ['TeamfightHealingDone'],
            ['TeamfightDamageTaken'],
            ['TeamfightHeroDamage'],
            ['EndOfMatchAwardGivenToNonwinner'],
            ['OnFireTimeOnFire'],
            ['TimeOnPoint'],
            ['TeamWinsDiablo'],
            ['TeamWinsFemale'],
            ['TeamWinsMale'],
            ['TeamWinsStarCraft'],
            ['TeamWinsWarcraft'],
            ['WinsWarrior'],
            ['WinsAssassin'],
            ['WinsSupport'],
            ['WinsSpecialist'],
            ['WinsStarCraft'],
            ['WinsDiablo'],
            ['WinsWarcraft'],
            ['WinsMale'],
            ['WinsFemale'],
            ['PlaysStarCraft'],
            ['PlaysDiablo'],
            ['PlaysOverwatch'],
            ['PlaysWarCraft'],
            ['PlaysWarrior'],
            ['PlaysAssassin'],
            ['PlaysSupport'],
            ['PlaysSpecialist'],
            ['PlaysMale'],
            ['PlaysFemale'],
            ['DragonNumberOfDragonCaptures'],
            ['DragonShrinesCaptured'],
            ['GardensSeedsCollected'],
            ['GardensPlantDamage'],
            ['AltarDamageDone'],
            ['DamageDoneToImmortal'],
            ['DamageDoneToShrineMinions'],
            ['GemsTurnedIn'],
            ['RavenTributesCollected'],
            ['CurseDamageDone'],
            ['MinesSkullsCollected'],
            ['BlackheartDoubloonsCollected'],
            ['BlackheartDoubloonsTurnedIn'],
            ['TimeInTemple'],
            ['DamageDoneToZerg'],
            ['NukeDamageDone'],
            ['TimeOnPayload'],
        ],
        FUNC => [
            ['game_length', BUILD_FIELD_DATA, GAME_MODE, GAME_LENGTH],
            ['game_total', BUILD_FIELD_DATA, GAME_MODE, INC],
            ['maps_length', BUILD_JSON_FIELD_DATA, MAP, GAME_LENGTH],
            ['maps_total', BUILD_JSON_FIELD_DATA, MAP, INC],
            ['game_win', BUILD_FIELD_DATA, GAME_MODE, INC, WIN],
            ['maps_win', BUILD_JSON_FIELD_DATA, MAP, INC, WIN],
            ['party_total', BUILD_FIELD_DATA, PARTY, INC, PARTY],
            ['party_win', BUILD_FIELD_DATA, PARTY, INC, PARTY_WIN],
            ['Level_count', BUILD_JSON_FIELD_DATA, SCORE_RESULT.SEP.'Level', INC],
            ['Takedowns_count', BUILD_JSON_FIELD_DATA, SCORE_RESULT.SEP.'Takedowns', INC],
            ['SoloKills_count', BUILD_JSON_FIELD_DATA, SCORE_RESULT.SEP.'SoloKills', INC],
            ['Assists_count', BUILD_JSON_FIELD_DATA, SCORE_RESULT.SEP.'Assists', INC],
            ['Deaths_count', BUILD_JSON_FIELD_DATA, SCORE_RESULT.SEP.'Deaths', INC],
            ['HighestKillStreak_count', BUILD_JSON_FIELD_DATA, SCORE_RESULT.SEP.'HighestKillStreak', INC],
            ['MatchAwards', BUILD_JSON_FIELD_DATA, SCORE_RESULT.SEP.'MatchAwards', INC],
        ],
    ];
}
